# -----------------------------------------------------------------------------
# 🧹 Pre-commit configuration
#
# Purpose:
#   Run formatters and linters automatically before every commit.
#   Keeps local dev, CI, and teammates perfectly aligned.
# -----------------------------------------------------------------------------
repos:
  # --- Black formatter -------------------------------------------------------
  - repo: https://github.com/psf/black
    rev: 24.10.0  # pick a stable release
    hooks:
      - id: black
        args: ["--line-length=88"]

  # --- isort import sorter ---------------------------------------------------
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # --- flake8 linter --------------------------------------------------------
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]

  # --- Optional: notebook cleaning ------------------------------------------
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args: ["--keep-output", "False"]
        files: "\\.ipynb$"

    # --- Run pytest (optional fast tests) -------------------------------------
  - repo: local
    hooks:
      - id: pytest
        name: pytest (unit tests)
        entry: pytest -q src/test --disable-warnings --maxfail=1
        language: system
        pass_filenames: false
