## CI workflow for running unit tests
##
## Purpose:
##   Run the project's unit-only tests in GitHub Actions. This job installs
##   dependencies and runs pytest only against `src/test` to avoid integration
##   tests that require external services (Neo4j, Ollama, etc.).
##
## Local usage:
##   To reproduce the CI steps locally, install dev dependencies and run:
##
##     python -m pip install -r requirements-dev.txt
##     # or use the helper script below which sets PYTHONPATH for tests:
##     python scripts/run_unit_tests.py
##
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run unit tests (src/test only)
        env:
          PYTHONPATH: src
        run: |
          pytest -q src/test
